# Generated by Django 4.1.7 on 2023-03-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Otaku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_anime', models.CharField(max_length=40)),
                ('Tipo_anime', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=120)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
