# Generated by Django 4.1.7 on 2023-03-24 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoAnime', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otaku',
            old_name='descripcion',
            new_name='Descripcion',
        ),
    ]
