# Generated by Django 4.1.7 on 2023-03-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoAnime', '0003_otaku_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='otaku',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='portada'),
        ),
    ]
