# Generated by Django 4.1.7 on 2023-03-28 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoAnime', '0004_otaku_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otaku',
            old_name='imagen',
            new_name='image',
        ),
    ]
